version: '2'
services:
    demo-mysql:
        image: mysql:5.7.18

        environment:
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=demo_123
            - MYSQL_DATABASE=demo_db
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
            - 3306:3306
